"""
Bilingual text dictionary — English / Arabic (complete)
GovInsight Streamlit App
"""
TEXT = {
    # ===== Navigation =====
    "nav_overview": {"en": "Overview", "ar": "نظرة عامة"},
    "nav_sentiment": {"en": "Sentiment", "ar": "تحليل المشاعر"},
    "nav_complaints": {"en": "Complaints", "ar": "الشكاوى"},
    "nav_priority": {"en": "Priority & Anomaly", "ar": "الأولويات والشذوذ"},
    "nav_predict": {"en": "Live Predict", "ar": "توقّع حي"},

    # ===== Sidebar =====
    "app_name": {"en": "GovInsight", "ar": "جوف إنسايت"},
    "app_tagline": {"en": "AI Feedback Intelligence", "ar": "ذكاء تحليل الآراء"},
    "reviews_analyzed": {"en": "reviews analyzed", "ar": "مراجعة محلّلة"},
    "services": {"en": "services", "ar": "خدمات"},
    "governorates": {"en": "governorates", "ar": "محافظة"},
    "model": {"en": "Model", "ar": "الموديل"},

    # ===== Overview =====
    "hero_title": {"en": "Government Services Intelligence", "ar": "ذكاء الخدمات الحكومية"},
    "hero_sub": {"en": "AI-powered analysis of 8,425 real citizen reviews · Egyptian public services",
                 "ar": "تحليل ذكي لـ 8,425 مراجعة حقيقية · الخدمات الحكومية المصرية"},
    "kpi_reviews": {"en": "Reviews Analyzed", "ar": "مراجعة محلّلة"},
    "kpi_negative": {"en": "Negative Sentiment", "ar": "نسبة السلبية"},
    "kpi_positive": {"en": "Positive Sentiment", "ar": "نسبة الإيجابية"},
    "kpi_rating": {"en": "Avg Star Rating", "ar": "متوسط التقييم"},
    "key_finding": {"en": "Key Finding — The Rating Paradox:", "ar": "الاكتشاف الرئيسي — تناقض التقييم:"},
    "paradox_text": {"en": "Despite an average star rating of {r}/5 (suggesting satisfaction), {n}% of review text is actually negative. Star ratings alone are misleading — NLP reveals the true voice of citizens.",
                     "ar": "رغم أن متوسط التقييم {r}/5 (يوحي بالرضا)، فإن {n}% من نصوص المراجعات سلبية فعلياً. التقييم الرقمي وحده مضلّل — والذكاء الاصطناعي يكشف الصوت الحقيقي للمواطن."},
    "sent_dist": {"en": "Sentiment Distribution", "ar": "توزيع المشاعر"},
    "neg_by_service": {"en": "Negativity by Service", "ar": "السلبية حسب الخدمة"},
    "overview_caveat": {"en": "Note: Sentiment labels were generated by an MSA-trained model, which may misclassify some Egyptian-dialect or negated phrases. Figures carry an inherent margin of error (validated at 85% agreement with human labeling).",
                        "ar": "ملاحظة: تصنيف المشاعر تمّ بموديل مدرّب على الفصحى، وقد يخطئ في بعض جمل العامية المصرية أو النفي. الأرقام تحمل هامش خطأ متأصّل (تم التحقق منها بنسبة اتفاق 85% مع التقييم البشري)."},

    # ===== Sentiment labels =====
    "negative": {"en": "Negative", "ar": "سلبي"},
    "positive": {"en": "Positive", "ar": "إيجابي"},
    "neutral": {"en": "Neutral", "ar": "محايد"},

    # ===== Service names =====
    "svc_civil": {"en": "Civil Registry", "ar": "السجل المدني"},
    "svc_traffic": {"en": "Traffic Unit", "ar": "وحدة المرور"},
    "svc_notary": {"en": "Real Estate Notary", "ar": "الشهر العقاري"},
    "svc_post": {"en": "Post Office", "ar": "مكتب البريد"},

    # ===== Sentiment page =====
    "sent_deep_sub": {"en": "Deep dive by governorate and time", "ar": "تحليل تفصيلي حسب المحافظة والزمن"},
    "filter_service": {"en": "Filter by service:", "ar": "فلترة حسب الخدمة:"},
    "all_services": {"en": "All Services", "ar": "كل الخدمات"},
    "sent_by_gov": {"en": "Negativity by Governorate", "ar": "السلبية حسب المحافظة"},
    "sent_over_time": {"en": "Sentiment Trend Over Time", "ar": "اتجاه المشاعر عبر الزمن"},
    "year": {"en": "Year", "ar": "السنة"},
    "trend_improve": {"en": "<b>Improving trend:</b> Negativity dropped from {a}% to {b}% — services are gradually improving.",
                      "ar": "<b>اتجاه تحسّن:</b> السلبية نزلت من {a}% إلى {b}% — الخدمات بتتحسّن تدريجياً."},
    "trend_worsen": {"en": "<b>Worsening trend:</b> Negativity rose from {a}% to {b}%.",
                     "ar": "<b>اتجاه تدهور:</b> السلبية زادت من {a}% إلى {b}%."},

    # ===== Complaints page =====
    "complaints_sub": {"en": "What citizens complain about most", "ar": "الناس بتشتكي من إيه أكتر"},
    "top_complaints": {"en": "Top Complaint Categories", "ar": "أكثر فئات الشكاوى"},
    "complaint_insight": {"en": "<b>{c}</b> is the #1 complaint across all services — a structural issue needing a national-level solution.",
                          "ar": "<b>{c}</b> هي الشكوى الأولى في كل الخدمات — أزمة هيكلية تحتاج حلاً على مستوى السياسة العامة."},
    "complaint_caveat": {"en": "Note: Complaint categories were detected via keyword matching — an interpretable but approximate method. Topic modeling (BERTopic/LDA) is a planned improvement.",
                         "ar": "ملاحظة: فئات الشكاوى اكتُشفت بمطابقة كلمات مفتاحية — طريقة قابلة للتفسير لكنها تقريبية. النمذجة الموضوعية (BERTopic/LDA) تحسين مخطّط له."},

    # ===== Priority & Anomaly page =====
    "priority_sub": {"en": "Data-driven intervention priorities", "ar": "أولويات التدخّل المبنية على البيانات"},
    "view_mode": {"en": "View:", "ar": "العرض:"},
    "view_worst": {"en": "⚠️ Needs Intervention (Worst)", "ar": "⚠️ تحتاج تدخّل (الأسوأ)"},
    "view_best": {"en": "🏆 Success Models (Best)", "ar": "🏆 نماذج النجاح (الأفضل)"},
    "worst_list": {"en": "Top 10 Offices Needing Intervention", "ar": "أعلى 10 مكاتب تحتاج تدخّل"},
    "best_list": {"en": "Top 10 Best-Performing Offices", "ar": "أعلى 10 مكاتب أداءً"},
    "priority_score": {"en": "Priority Score", "ar": "درجة الأولوية"},
    "pos_score": {"en": "Excellence Score", "ar": "درجة التميّز"},
    "best_insight": {"en": "These offices excel — studying <b>why</b> they succeed (staff, location, management) could reveal replicable best practices.",
                     "ar": "المكاتب دي متميّزة — دراسة <b>ليه</b> نجحت (موظفين، مكان، إدارة) ممكن تكشف ممارسات قابلة للتعميم."},
    "anomaly_title": {"en": "Statistical Anomalies", "ar": "الشذوذ الإحصائي"},
    "anom_bad": {"en": "⚠️ Struggling", "ar": "⚠️ متعثّر"},
    "anom_good": {"en": "✅ Exemplary", "ar": "✅ متميّز"},
    "col_service": {"en": "Service", "ar": "الخدمة"},
    "col_gov": {"en": "Governorate", "ar": "المحافظة"},
    "col_neg": {"en": "Negative %", "ar": "السلبية %"},
    "col_rating": {"en": "Avg Rating", "ar": "التقييم"},
    "col_reviews": {"en": "Reviews", "ar": "المراجعات"},
    "col_type": {"en": "Type", "ar": "النوع"},
    "anomaly_insight": {"en": "Anomaly detection found two types: <b>struggling</b> offices needing urgent action, and <b>exemplary</b> ones worth studying as success models.",
                        "ar": "اكتشاف الشذوذ حدّد نوعين: مكاتب <b>متعثّرة</b> تحتاج تدخّلاً عاجلاً، ومكاتب <b>متميّزة</b> تستحق الدراسة كنماذج نجاح."},

    # ===== Live Predict =====
    "model_light": {"en": "Lightweight Model", "ar": "الموديل الخفيف"},
    "model_advanced": {"en": "Advanced (MARBERT)", "ar": "المتقدّم (MARBERT)"},
    "light_desc": {"en": "TF-IDF + Logistic · 78.9%", "ar": "سريع · دقّة 78.9%"},
    "advanced_desc": {"en": "Transformer · dialect-aware", "ar": "يفهم العامية المصرية"},
    "loading_marbert": {"en": "Loading MARBERT...", "ar": "بنحمّل MARBERT..."},
    "agree": {"en": "Both models agree ✓", "ar": "الموديلان متفقان ✓"},
    "disagree": {"en": "Models disagree — dialect may be the reason", "ar": "الموديلان مختلفان — العامية قد تكون السبب"},
    "predict_title": {"en": "Live Sentiment Prediction", "ar": "التنبؤ الحي بالمشاعر"},
    "predict_sub": {"en": "Type any Arabic review — compare two AI models instantly",
                    "ar": "اكتب أي مراجعة عربية — قارن بين موديلين فوراً"},
    "predict_input": {"en": "Enter Arabic text:", "ar": "اكتب النص العربي:"},
    "predict_btn": {"en": "Analyze Sentiment", "ar": "حلّل المشاعر"},
    "confidence": {"en": "Confidence", "ar": "درجة الثقة"},
    "model_info": {"en": "Comparing a lightweight model (TF-IDF) vs an advanced transformer (MARBERT, dialect-aware)",
                   "ar": "مقارنة بين موديل خفيف (TF-IDF) وموديل transformer متقدّم (MARBERT يفهم العامية)"},
    "try_examples": {"en": "Try these examples:", "ar": "جرّب الأمثلة دي:"},
    "empty_warn": {"en": "Please enter some text first.", "ar": "اكتب نص الأول من فضلك."},
    "arabic_only": {"en": "This model works with Arabic text only. Please enter Arabic.",
                    "ar": "الموديل بيشتغل بالعربي بس. اكتب نص عربي من فضلك."},
    "marbert_error": {"en": "MARBERT is not available in this deployment (runs locally with torch installed). The lightweight model is shown.",
                      "ar": "MARBERT غير متاح في هذه النسخة المنشورة (يعمل محلياً مع torch). يظهر الموديل الخفيف."},

    # ===== Common =====
    "coming_soon": {"en": "Coming Soon", "ar": "قريباً"},
}


def t(key, lang, **kwargs):
    """Get translated text. lang = 'en' or 'ar'. kwargs for {placeholder} formatting."""
    txt = TEXT.get(key, {}).get(lang, key)
    if kwargs:
        try:
            txt = txt.format(**kwargs)
        except Exception:
            pass
    return txt